- name: Firewall

  hosts: all
  remote_user: agent
  become: true

  tasks:
    - name: Allow access to port HTTP/80
      community.general.ufw: 
        rule: allow 
        port: http

    - name: Allow access to port HTTPS/443
      community.general.ufw:
        rule: allow
        port: https

    - name: Allow access to port 8080 (Traefik HTTP)
      community.general.ufw: 
        rule: allow 
        port: 8080

    - name: Allow access to port 8443 (Traefik HTTPS)
      community.general.ufw:
        rule: allow
        port: 8443

    - name: Enable port forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
    
    - name: Add port forwarding rules
      ansible.builtin.blockinfile:
        path: /etc/ufw/before.rules
        insertbefore: BOF
        block: |
          *nat
          :PREROUTING ACCEPT [0:0]
          -A PREROUTING -p tcp --dport 80  -j REDIRECT --to-port 8080
          -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8443
          -A OUTPUT -o lo -p tcp --dport 80 -j REDIRECT --to-port 8080
          -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8443
          COMMIT

    - name: Reload UFW
      community.general.ufw:
        default: deny
        state: reloaded
